### ISSUE TITLE
Production log configuration folder is set to file name

### ISSUE THREAD

**Issue by meywood** [stormeye2000/cspr-events-store#62]
```
logging:
  level:
    com:
      stormeye: ${LOG_LEVEL:INFO}
  file:
    path: /var/logs/store.log

```

The above path should reference a folder eg /var/logs/store-consumer
